[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = 'probe-rs run --chip STM32H563ZITx --probe 0483:374e:0027002C3133511437363734'

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "trace"
